// ============================================================
// 产品数据 - Guangwei Optics（全面升级版）
// ============================================================
import { Product, Language } from './types';

export type ProductCategory = string;

export const products: Product[] = [
  {
    id: 'aviator-gold-001',
    name: {
      en: 'Classic Aviator — Gold Metal Frame',
      zh: '经典飞行员款 — 金色金属框',
      es: 'Aviador Clásico — Marco Dorado Metálico',
      fr: 'Aviateur Classique — Monture Dorée Métal',
      pt: 'Aviador Clássico — Armação Dourada Metálica',
      ru: 'Классический Авиатор — Золотая Металлическая Оправа',
    },
    shortDesc: {
      en: 'Timeless pilot design. Premium gold-plated metal frame with polarized lenses.',
      zh: '永恒的飞行员设计。优质镀金金属框，偏光镜片。',
      es: 'Diseño piloto atemporal. Montura metálica dorada premium con lentes polarizadas.',
      fr: 'Design pilote intemporel. Monture métallique dorée premium avec verres polarisés.',
      pt: 'Design piloto clássico. Armação metálica dourada premium com lentes polarizadas.',
      ru: 'Нестареющий дизайн пилота. Премиальная золотая металлическая оправа с поляризованными линзами.',
    },
    description: {
      en: 'The definitive aviator — the style that never goes out of fashion. Our gold-plated metal frame combines aerospace-grade alloy with hand-polished surfaces for a frame that\'s both lightweight (28g) and structurally rigid. Fitted with polarized CR39 lenses that eliminate 99% of glare while maintaining true color perception. UV400 protection on both UVA and UVB wavelengths. The tear-drop lens shape flatters most face shapes, making this our most popular OEM style for established brands.\n\nIdeal for: Retail chains, optical stores, department store concessions, fashion brands.',
      zh: '最经典的飞行员款式——永不过时的设计。我们的金色电镀金属框结合航空级合金与手工抛光表面，打造出轻盈（28g）且结构坚固的镜框。配备偏光CR39镜片，消除99%眩光同时保持真实色彩感知。UVA和UVB双防护。泪滴形镜片适合大多数脸型，是我们最受欢迎的OEM款式。\n\n适用：零售连锁、眼镜店、百货专柜、时尚品牌。',
      es: 'El aviador definitivo — el estilo que nunca pasa de moda. Montura metálica金色镀金 con aleación de grado aeroespacial y superficies pulidas a mano. Lentes polarizados CR39 que eliminan el 99% del deslumbramiento.',
      fr: "Le définition de l'aviateur — un style qui ne se démode jamais. Monture métallique dorée de qualité aérospatiale avec surfaces polies à la main.",
      pt: 'O aviador definitivo — estilo que nunca sai de moda. Armação metálica dourada de grau aeroespacial com superfícies polidas à mão.',
      ru: 'Определяющий авиатор — стиль, который никогда не выходит из моды. Золотая металлическая оправа аэрокосмического класса.',
    },
    price: '$3.50–8.00',
    priceRaw: { min: 3.5, max: 8.0, currency: 'USD' },
    moq: 3000,
    category: 'classic-aviator',
    tags: ['Unisex', 'Metal', 'Polarized', 'UV400', 'Bestseller'],
    images: [
      'https://picsum.photos/seed/aviator-gold-main/800/600',
      'https://picsum.photos/seed/aviator-gold-side/800/600',
      'https://picsum.photos/seed/aviator-gold-lens/800/600',
      'https://picsum.photos/seed/aviator-gold-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Metal Alloy, 18K Gold-plated',
      'Lens Material': 'Polarized CR39, 1.5mm',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Frame Width': '140mm',
      'Lens Height': '48mm',
      'Bridge': '14mm',
      'Temple Length': '140mm',
      'Weight': '28g',
      'Min Order': '3,000 pcs/model',
      'Production Time': '20–25 days',
      'Certifications': 'CE, FDA, ISO9001',
    },
    featured: true,
    badge: 'Bestseller',
    moqTiers: [
      { qty: '3,000–4,999', price: '$7.00–8.00' },
      { qty: '5,000–9,999', price: '$5.00–6.50' },
      { qty: '10,000+', price: '$3.50–5.00' },
    ],
  },
  {
    id: 'aviator-silver-001',
    name: {
      en: 'Classic Aviator — Brushed Silver',
      zh: '经典飞行员款 — 刷砂银',
      es: 'Aviador Clásico — Plata Cepillada',
      fr: 'Aviateur Classique — Argent Brossé',
      pt: 'Aviador Clássico — Prata Escovada',
      ru: 'Классический Авиатор — Матовое Серебро',
    },
    shortDesc: {
      en: 'The same iconic pilot design in sophisticated brushed silver metal.',
      zh: '相同标志性飞行员设计，精致刷砂银色金属。',
      es: 'El mismo diseño icónico de piloto en metal plateado cepillado.',
      fr: "Le même design pilote emblématique en métal argenté brossé.",
      pt: 'O mesmo design icônico de piloto em metal prateado escovado.',
      ru: 'Та же культовая модель пилота в изысканном матовом серебре.',
    },
    description: {
      en: 'Sophisticated brushed silver metal with the same proven aviator geometry. The neutral silver tone makes this the easiest style to merchandise across different market segments — from European fashion to American sports retail. Anti-corrosion coating ensures the frame survives humid climates without tarnishing. Compatible with our custom logo temple printing and embossing services.',
      zh: '精致的刷砂银色，相同成熟的飞行员几何形状。中性的银色调使其成为最容易在不同市场细分中销售的款式。抗腐蚀涂层确保镜框在潮湿气候下不会失去光泽。支持定制logo镜腿印刷和压印服务。',
      es: 'Plata cepillada sofisticada con la misma geometría probada. El tono neutral plata facilita la comercialización en diferentes segmentos.',
      fr: "Argent brossé sophistiqué avec la même géométrie éprouvée. Le ton neutre silver facilite la commercialisation.",
      pt: 'Prata escovada sofisticada com a mesma geometria comprovada. O tom neutro prateado facilita a comercialização.',
      ru: 'Изысканное матовое серебро с той же проверенной геометрией. Нейтральный серебристый тон легко продаётся в разных сегментах.',
    },
    price: '$3.20–7.00',
    priceRaw: { min: 3.2, max: 7.0, currency: 'USD' },
    moq: 3000,
    category: 'classic-aviator',
    tags: ['Unisex', 'Metal', 'UV400', 'Anti-corrosion'],
    images: [
      'https://picsum.photos/seed/aviator-silver-main/800/600',
      'https://picsum.photos/seed/aviator-silver-side/800/600',
      'https://picsum.photos/seed/aviator-silver-lens/800/600',
      'https://picsum.photos/seed/aviator-silver-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Metal Alloy, Brushed Silver',
      'Lens Material': 'CR39, 1.5mm',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Frame Width': '140mm',
      'Lens Height': '46mm',
      'Bridge': '14mm',
      'Temple Length': '140mm',
      'Weight': '26g',
      'Min Order': '3,000 pcs/model',
      'Production Time': '20–25 days',
      'Certifications': 'CE, FDA, ISO9001',
    },
    featured: true,
    badge: '',
    moqTiers: [
      { qty: '3,000–4,999', price: '$6.00–7.00' },
      { qty: '5,000–9,999', price: '$4.50–6.00' },
      { qty: '10,000+', price: '$3.20–4.50' },
    ],
  },
  {
    id: 'sport-tr90-001',
    name: {
      en: 'Sport Performance — TR90 Wraparound',
      zh: '运动款 — TR90环绕式',
      es: 'Deportivo Rendimineto — TR90 envolvente',
      fr: 'Sport Performance — TR90 Enveloppant',
      pt: 'Esportivo Performance — TR90 Envolto',
      ru: 'Спортивный Производительность — TR90 Обхватывающий',
    },
    shortDesc: {
      en: 'Impact-resistant TR90 frame with polarized TAC lenses. Anti-slip rubber coatings.',
      zh: '抗冲击TR90镜框，偏光TAC镜片，防滑橡胶涂层。',
      es: 'Montura TR90 resistente a impactos con lentes TAC polarizadas. Revestimientos de goma antideslizantes.',
      fr: 'Monture TR90 antichoc avec verres TAC polarisés. Revêtements en caoutchouc antidérapants.',
      pt: 'Armação TR90 resistente a impactos com lentes TAC polarizadas. Revestimentos de borracha antiderrapantes.',
      ru: 'Ударопрочная TR90 оправа с поляризованными TAC линзами. Антискользящее резиновое покрытие.',
    },
    description: {
      en: 'Built for athletes who demand both performance and comfort. The TR90 nylon frame is virtually unbreakable under impact — passing ANSI Z87.1 high-velocity impact testing. Wraparound design blocks wind and peripheral glare. Anti-slip rubber temples and nose pads stay put during running, cycling, or fishing. Polarized TAC lenses cut water and road glare by 99%. Available in 8 frame colors with 3 lens options per color.',
      zh: '为追求性能和舒适的运动员打造。TR90尼龙框抗冲击，通过ANSI Z87.1高速冲击测试。环绕式设计阻挡风和侧面眩光。防滑橡胶镜腿和鼻托在跑步、骑行、钓鱼时稳固。偏光TAC镜片消除99%水面和道路眩光。8种框色可选，每色3种镜片。',
      es: 'Diseñado para atletas que exigen rendimiento y comodidad. TR90 irrompible bajo impacto. Diseño envolvente bloquea viento y deslumbramiento.',
      fr: "Conçu pour les athlètes qui exigent performance et confort. TR90 incassable sous impact. Design enveloppant bloque le vent.",
      pt: 'Construído para atletas que exigem desempenho e conforto. TR90 inquebrável sob impacto. Design envolvente bloqueia vento.',
      ru: 'Создан для спортсменов, требующих производительности и комфорта. TR90 практически неразрушим при ударе.',
    },
    price: '$4.20–9.50',
    priceRaw: { min: 4.2, max: 9.5, currency: 'USD' },
    moq: 3000,
    category: 'sport',
    tags: ['Sports', 'TR90', 'Polarized', 'Impact Resistant', 'Wraparound'],
    images: [
      'https://picsum.photos/seed/sport-tr90-main/800/600',
      'https://picsum.photos/seed/sport-tr90-active/800/600',
      'https://picsum.photos/seed/sport-tr90-lens/800/600',
      'https://picsum.photos/seed/sport-tr90-pack/800/600',
    ],
    specs: {
      'Frame Material': 'TR90 Nylon (Swiss-grade)',
      'Lens Material': 'Polarized TAC, 1.1mm',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Impact Resistance': 'ANSI Z87.1 Passed',
      'Frame Width': '145mm',
      'Lens Height': '42mm',
      'Weight': '32g',
      'Anti-slip': 'TPR Rubber Coating',
      'Colors Available': '8 frames × 3 lenses',
      'Min Order': '3,000 pcs/model',
      'Production Time': '25–30 days',
      'Certifications': 'CE, FDA, ANSI Z87.1',
    },
    featured: true,
    badge: 'Sport Pick',
    moqTiers: [
      { qty: '3,000–4,999', price: '$8.00–9.50' },
      { qty: '5,000–9,999', price: '$6.00–8.00' },
      { qty: '10,000+', price: '$4.20–6.00' },
    ],
  },
  {
    id: 'cat-eye-acetate-001',
    name: {
      en: 'Cat Eye — Italian Acetate Fashion',
      zh: '猫眼款 — 意大利板材时尚',
      es: 'Ojo de Gato — Moda Acetato Italiano',
      fr: 'Chat Œil — Mode Acétate Italien',
      pt: 'Olho de Gato — Moda Acetato Italiano',
      ru: 'Кошачий Глаз — Мода Итальянский Ацетат',
    },
    shortDesc: {
      en: 'Trendy women\'s cat eye in premium Italian acetate. 12 colors available.',
      zh: '时尚女性猫眼，优质意大利板材。12色可选。',
      es: 'Ojo de gato femenino de moda en acetato italiano premium. 12 colores.',
      fr: 'Design œil de chat tendance pour femmes en acétate italien premium. 12 couleurs.',
      pt: 'Olho de gato feminino moderno em acetato italiano premium. 12 cores.',
      ru: 'Трендовый женский кошачий глаз из премиального итальянского ацетата. 12 цветов.',
    },
    description: {
      en: 'Italian Mazzucchelli acetate — the gold standard of eyewear plastics. Each frame is hand-polished from raw slabs to a high-gloss finish that\'s impossible to replicate with injection molding. The cat eye shape is universally flattering and has been our top-selling women\'s style for 5 consecutive years. The frame accepts laser engraving, metal logo plaques, and custom hinge decorations. Available in 12 tortoise, solid, and gradient colorways.',
      zh: '意大利Mazzucchelli板材——眼镜塑料的金标准。每一副镜框都经过手工抛光，从原材料到高光表面。猫眼形状适合各种脸型，连续5年成为女性最畅销款式。支持激光雕刻、金属logo铭牌和定制铰链装饰。12种龟甲色、纯色和渐变色可选。',
      es: 'Acetato italiano Mazzucchelli — el estándar de calidad. Cada montura se pule a mano. La forma de ojo de gato favorece a todos.',
      fr: "Acétate italien Mazzucchelli — la référence. Chaque monture polie à la main. Forme œil de chat universellement flatteuse.",
      pt: 'Acetato italiano Mazzucchelli — o padrão ouro. Cada armação polida à mão. Formato olho de gato universalmente favorecedor.',
      ru: 'Итальянский ацетат Mazzucchelli — золотой стандарт. Каждая оправа полируется вручную. Форма «кошачий глаз» подходит всем.',
    },
    price: '$3.80–8.80',
    priceRaw: { min: 3.8, max: 8.8, currency: 'USD' },
    moq: 3000,
    category: 'cat-eye',
    tags: ['Women', 'Acetate', 'Italian', 'Fashion', 'High-gloss'],
    images: [
      'https://picsum.photos/seed/cateye-acetate-main/800/600',
      'https://picsum.photos/seed/cateye-acetate-side/800/600',
      'https://picsum.photos/seed/cateye-acetate-detail/800/600',
      'https://picsum.photos/seed/cateye-acetate-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Mazzucchelli Italian Acetate',
      'Lens Material': 'CR39, 1.5mm',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Frame Width': '138mm',
      'Lens Height': '44mm',
      'Bridge': '14mm',
      'Weight': '30g',
      'Colors Available': '12 colorways',
      'Custom Options': 'Engraving, logo plaques',
      'Min Order': '3,000 pcs/model',
      'Production Time': '25–30 days',
      'Certifications': 'CE, FDA',
    },
    featured: true,
    badge: 'Women\'s Top',
    moqTiers: [
      { qty: '3,000–4,999', price: '$7.50–8.80' },
      { qty: '5,000–9,999', price: '$5.50–7.50' },
      { qty: '10,000+', price: '$3.80–5.50' },
    ],
  },
  {
    id: 'kids-safe-001',
    name: {
      en: 'Kids Safe — BPA-Free Shatterproof 3-12Y',
      zh: '儿童安全款 — BPA-free防碎 3-12岁',
      es: 'Infantil Seguro — Anti-roturo BPA-Free 3-12A',
      fr: 'Enfants Sûr — Incassable Sans BPA 3-12Ans',
      pt: 'Infantil Seguro — Inquebrável Sem BPA 3-12A',
      ru: 'Детские Безопасные — Без BPA Небьющиеся 3-12Лет',
    },
    shortDesc: {
      en: 'BPA-free, shatterproof lenses. CE/FDA certified for children. Adjustable strap.',
      zh: 'BPA-free，防碎镜片。CE/FDA儿童认证。可调节绑带。',
      es: 'Sin BPA, lentes irrompibles. Certificado CE/FDA para niños. Correa ajustable.',
      fr: 'Sans BPA, verres incassables. Certifié CE/FDA pour enfants. Courroie ajustable.',
      pt: 'Sem BPA, lentes inquebráveis. Certificado CE/FDA para crianças. Alça ajustável.',
      ru: 'Без BPA, небьющиеся линзы. CE/FDA сертификация для детей. Регулируемый ремешок.',
    },
    description: {
      en: 'When parents buy sunglasses for kids, safety is the #1 concern. That\'s why we built this with polycarbonate lenses that pass FDA 21 CFR 801.410 impact resistance — the same standard used for safety glasses in industrial applications. The flexible TR90 frame snaps back to shape even after a hard bend. No metal parts anywhere. Adjustable elastic strap means a custom fit from age 3 to 12. Available in 6 bright fun colors, individually blister-packed with a cleaning cloth and mini case.',
      zh: '家长购买儿童太阳镜时，安全性是第一关注点。我们的镜片通过FDA 21 CFR 801.410抗冲击测试——与工业安全眼镜相同的标准。柔韧的TR90镜框即使弯曲也能恢复原状。全身无金属件。可调节松紧带适合3-12岁。6种明亮颜色，每副独立吸塑包装含眼镜布和小眼镜盒。',
      es: 'Seguridad #1 para padres. Lentes de policarbonato que pasan la prueba de resistencia al impacto FDA. Sin piezas metálicas.',
      fr: 'Sécurité #1 pour les parents. Lentilles en polycarbonate conformes FDA. Sans pièces métalliques.',
      pt: 'Segurança #1 para os pais. Lentes de policarbonato que passam no teste FDA. Sem peças metálicas.',
      ru: 'Безопасность — главная забота родителей. Поликарбонатные линзы проходят тест FDA. Без металлических деталей.',
    },
    price: '$2.50–5.00',
    priceRaw: { min: 2.5, max: 5.0, currency: 'USD' },
    moq: 5000,
    category: 'kids',
    tags: ['Kids', 'BPA-Free', 'Shatterproof', 'CE', 'FDA', 'Safe'],
    images: [
      'https://picsum.photos/seed/kids-safe-main/800/600',
      'https://picsum.photos/seed/kids-safe-active/800/600',
      'https://picsum.photos/seed/kids-safe-colors/800/600',
      'https://picsum.photos/seed/kids-safe-pack/800/600',
    ],
    specs: {
      'Frame Material': 'TR90 Nylon (Flexible)',
      'Lens Material': 'Polycarbonate (Shatterproof)',
      'UV Protection': 'UV400 (UVA + UVB)',
      'BPA Free': 'Yes — Full Test Report',
      'Impact Test': 'FDA 21 CFR 801.410 ✓',
      'Age Range': '3–12 Years',
      'Strap': 'Adjustable Elastic (38–52cm)',
      'Frame Width': '120mm',
      'Lens Height': '38mm',
      'Colors Available': '6 fun colors',
      'Min Order': '5,000 pcs/model',
      'Production Time': '20–25 days',
      'Certifications': 'CE, FDA, CPSIA, REACH',
    },
    featured: true,
    badge: 'Parent-Approved',
    moqTiers: [
      { qty: '5,000–9,999', price: '$4.00–5.00' },
      { qty: '10,000–19,999', price: '$3.00–4.00' },
      { qty: '20,000+', price: '$2.50–3.00' },
    ],
  },
  {
    id: 'luxury-titanium-001',
    name: {
      en: 'Luxury Round — Pure Titanium 18g',
      zh: '奢华圆框 — 纯钛18g',
      es: 'Lujo Redondo — Titanio Puro 18g',
      fr: 'Luxe Rond — Titane Pur 18g',
      pt: 'Luxo Redondo — Titânio Puro 18g',
      ru: 'Люкс Круглый — Чистый Титан 18г',
    },
    shortDesc: {
      en: 'Ultra-lightweight pure Grade 5 titanium. Hypoallergenic. Minimalist luxury.',
      zh: '超轻纯钛5级镜框。低过敏性。极简奢华。',
      es: 'Titanio puro ultra ligero Grado 5. Hipoalergénico. Lujo minimalista.',
      fr: 'Titane pur ultra léger Grade 5. Hypoallergénique. Luxe minimaliste.',
      pt: 'Titânio puro ultra leve Grau 5. Hipoalergênico. Luxo minimalista.',
      ru: 'Сверхлёгкий чистый титан 5 класса. Гипоаллергенный. Минималистичная роскошь.',
    },
    description: {
      en: 'At 18 grams, this is the lightest frame we produce — and one of the lightest in the industry. Grade 5 titanium (Ti-6Al-4V) is the same alloy used in aerospace and medical implants. It\'s stronger than steel at a fraction of the weight, completely hypoallergenic, and resistant to salt water corrosion. The minimalist round design appeals to the luxury consumer who values understatement over flash. This is the frame that converts customers into brand advocates.',
      zh: '18克——这是我们生产的最轻镜框，也是行业最轻之一。5级钛（Ti-6Al-4V）与航空和医疗植入物使用的合金相同。比钢更坚固，重量却只有一小部分，完全低过敏性，抗盐水腐蚀。极简圆形设计吸引追求低调奢华的消费者。是让客户成为品牌拥护者的款式。',
      es: '18 gramos — la montura más ligera que producimos. Titanio Grado 5, el mismo usado en aeroespacial. Hipoalergénico.',
      fr: '18 grammes — la monture la plus légère que nous produisons. Titane Grade 5 comme en	aérospatiale. Hypoallergénique.',
      pt: '18 gramas — a armação mais leve que produzimos. Titânio Grau 5, o mesmo usado em aeroespacial. Hipoalergênico.',
      ru: '18 грамм — самая лёгкая оправа, которую мы производим. Титан 5 класса, как в аэрокосмической отрасли. Гипоаллергенный.',
    },
    price: '$12.00–28.00',
    priceRaw: { min: 12.0, max: 28.0, currency: 'USD' },
    moq: 1000,
    category: 'luxury',
    tags: ['Luxury', 'Titanium', 'Hypoallergenic', 'Ultra-light', 'Polarized'],
    images: [
      'https://picsum.photos/seed/luxury-titanium-main/800/600',
      'https://picsum.photos/seed/luxury-titanium-detail/800/600',
      'https://picsum.photos/seed/luxury-titanium-side/800/600',
      'https://picsum.photos/seed/luxury-titanium-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Grade 5 Titanium (Ti-6Al-4V)',
      'Lens Material': 'Polarized Mineral Glass',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Frame Width': '138mm',
      'Lens Height': '40mm',
      'Bridge': '18mm',
      'Temple Length': '145mm',
      'Weight': '18g (ultra-light)',
      'Hypoallergenic': '100% — No nickel, no allergies',
      'Salt Water Proof': 'Yes — Marine grade',
      'Min Order': '1,000 pcs/model',
      'Production Time': '30–35 days',
      'Certifications': 'CE, FDA, ISO9001',
    },
    featured: true,
    badge: 'Ultra-Premium',
    moqTiers: [
      { qty: '1,000–2,999', price: '$22.00–28.00' },
      { qty: '3,000–4,999', price: '$16.00–22.00' },
      { qty: '5,000+', price: '$12.00–16.00' },
    ],
  },
  {
    id: 'fashion-shield-001',
    name: {
      en: 'One-Piece Shield — Beach & Water Sports',
      zh: '一体式盾牌 — 海滩及水上运动',
      es: 'Escudo Monobloque — Playa y Deportes Acuáticos',
      fr: 'Shield Une Pièce — Plage et Sports Nautiques',
      pt: 'Shield Peça Única — Praia e Esportes Aquáticos',
      ru: 'Цельный Щит — Пляж и Водные Виды Спорта',
    },
    shortDesc: {
      en: 'One-piece frameless shield. 22g ultra-light TR90. Popular beach style.',
      zh: '一体式无框盾牌。22g超轻TR90。热门海滩款式。',
      es: 'Escudo monobloque sin montura. TR90 ultra ligero 22g. Estilo playero popular.',
      fr: 'Shield monobloc sans monture. TR90 ultra léger 22g. Style plage populaire.',
      pt: 'Shield monobloc sem armação. TR90 ultra leve 22g. Estilo praia popular.',
      ru: 'Бескаркасный щит. 22г ультралёгкий TR90. Популярный пляжный стиль.',
    },
    description: {
      en: 'The one-piece shield is the definitive beach sunglasses — no frame lines, no gaps, maximum peripheral vision. The frameless construction eliminates pressure points for all-day comfort. Injection-molded from Swiss TR90 for consistent quality at scale. Popular with surf shops, beach resorts, and active lifestyle brands.',
      zh: '一体式盾牌是经典海滩太阳镜——无框线条、无缝隙、最大周边视野。无框结构消除压力点，全天佩戴舒适。瑞士TR90注塑成型，规模化品质一致。受冲浪店、海滩度假村和运动生活方式品牌欢迎。',
      es: 'El escudo monobloque es el definitivo gafas de playa — sin líneas de montura, sin huecos.',
      fr: 'Le shield monobloc est le definitive lunette de plage — sans ligne de monture, sans espace.',
      pt: 'O shield monobloc é o óculos de praia definitivo — sem linhas de armação, sem lacunas.',
      ru: 'Цельный щит — это классические пляжные очки — без линий оправы, без зазоров.',
    },
    price: '$3.00–6.00',
    priceRaw: { min: 3.0, max: 6.0, currency: 'USD' },
    moq: 3000,
    category: 'fashion',
    tags: ['Shield', 'One-Piece', 'Beach', 'TR90', 'Unisex', 'Lightweight'],
    images: [
      'https://picsum.photos/seed/shield-main/800/600',
      'https://picsum.photos/seed/shield-beach/800/600',
      'https://picsum.photos/seed/shield-lens/800/600',
      'https://picsum.photos/seed/shield-pack/800/600',
    ],
    specs: {
      'Frame Material': 'TR90 Grilamid (Swiss)',
      'Lens Material': 'Polycarbonate, 2mm shield',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Frame Width': '150mm',
      'Lens Height': '58mm',
      'Weight': '22g',
      'Peripheral Vision': '180° unblocked',
      'Colors Available': '6 solid colors',
      'Min Order': '3,000 pcs/model',
      'Production Time': '20–25 days',
      'Certifications': 'CE, FDA',
    },
    featured: false,
    badge: 'Beach Best',
    moqTiers: [
      { qty: '3,000–4,999', price: '$5.00–6.00' },
      { qty: '5,000–9,999', price: '$4.00–5.00' },
      { qty: '10,000+', price: '$3.00–4.00' },
    ],
  },
  {
    id: 'polarized-fishing-001',
    name: {
      en: 'Fishing Pro — 99% Glare Elimination',
      zh: '钓鱼专业款 — 消除99%眩光',
      es: 'Pesca Pro — Eliminación 99% Deslumbramiento',
      fr: 'Pêche Pro — Élimination Reflet 99%',
      pt: 'Pesca Pro — Eliminação 99% Brilho',
      ru: 'Рыбалка Про — Устранение 99% Бликов',
    },
    shortDesc: {
      en: 'Polarized TAC 1.1mm lenses eliminate 99% glare from water. Side shields included.',
      zh: '偏光TAC 1.1mm镜片消除99%水面眩光。含侧挡板。',
      es: 'Lentes TAC polarizados 1.1mm eliminan 99% del deslumbramiento del agua. Protectores laterales incluidos.',
      fr: 'Lentilles TAC polarisées 1.1mm éliminent 99% des reflets. Protections latérales incluses.',
      pt: 'Lentes TAC polarizados 1.1mm eliminam 99% do brilho da água. Protetores laterais incluídos.',
      ru: 'Поляризованные TAC линзы 1.1mm устраняют 99% бликов от воды. Боковые щитки в комплекте.',
    },
    description: {
      en: 'Serious anglers know: polarized lenses aren\'t a luxury, they\'re essential. See below the water\'s surface to spot fish, read structures, and track lure movement. Our 1.1mm TAC lenses are 40% thicker than standard 0.75mm polarized lenses — they resist scratching from hooks and leaders. The wraparound frame with removable side shields blocks glare from all angles. Anti-fog ventilation ports keep vision clear when you\'re working hard in humid conditions.',
      zh: '认真的钓鱼者知道：偏光镜片不是奢侈品，而是必需品。看清水面下，发现鱼群、读懂结构、追踪拟饵动向。我们的1.1mm TAC镜片比标准0.75mm偏光镜片厚40%——耐鱼钩和子线刮擦。环绕式框配可拆卸侧板阻挡各个角度的眩光。防雾通风孔在潮湿环境中保持视野清晰。',
      es: 'Los pescadores serios saben: las lentes polarizadas son esenciales, no un lujo. Vea bajo la superficie del agua.',
      fr: 'Les pêcheurs sérieux savent : les verres polarisés sont essentiels, pas un luxe.',
      pt: 'Pescadores sérios sabem: lentes polarizadas não são luxo, são essenciais.',
      ru: 'Серьёзные рыбаки знают: поляризованные линзы — это не роскошь, а необходимость.',
    },
    price: '$5.00–12.00',
    priceRaw: { min: 5.0, max: 12.0, currency: 'USD' },
    moq: 3000,
    category: 'polarized',
    tags: ['Polarized', 'Fishing', 'Wraparound', 'Anti-fog', 'Side Shields'],
    images: [
      'https://picsum.photos/seed/fishing-main/800/600',
      'https://picsum.photos/seed/fishing-water/800/600',
      'https://picsum.photos/seed/fishing-lens/800/600',
      'https://picsum.photos/seed/fishing-pack/800/600',
    ],
    specs: {
      'Frame Material': 'TR90 + TPR Anti-slip',
      'Lens Material': 'Polarized TAC, 1.1mm (thick)',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Glare Elimination': '99%',
      'Anti-fog': 'Ventilation Ports',
      'Side Shields': 'Removable — included',
      'Wraparound': 'Yes — full coverage',
      'Frame Width': '148mm',
      'Lens Height': '44mm',
      'Weight': '34g',
      'Min Order': '3,000 pcs/model',
      'Production Time': '25–30 days',
      'Certifications': 'CE, FDA',
    },
    featured: false,
    badge: 'Angler\'s Choice',
    moqTiers: [
      { qty: '3,000–4,999', price: '$9.50–12.00' },
      { qty: '5,000–9,999', price: '$7.00–9.50' },
      { qty: '10,000+', price: '$5.00–7.00' },
    ],
  },
  {
    id: 'retro-square-001',
    name: {
      en: 'Retro Square — 80s Bold Acetate',
      zh: '复古方框 — 80年代大胆板材',
      es: 'Cuadrado Retro — Acetato Audo Años 80',
      fr: 'Carré Rétro — Acétate Audacieux Années 80',
      pt: 'Quadrado Retrô — Acetato Ousado Anos 80',
      ru: 'Квадратный Ретро — Смелый Ацетат 80-х',
    },
    shortDesc: {
      en: 'Bold square frame inspired by 80s vintage. Thick Italian acetate. Unisex.',
      zh: '大胆方框，80年代复古灵感。厚意大利板材。中性款。',
      es: 'Montura cuadrada audaz inspirada en los 80. Acetato italiano grueso. Unisex.',
      fr: 'Monture carrée audacieuse inspirée des années 80. Acétate italien épais. Unisexe.',
      pt: 'Armação quadrada ousada inspirada nos anos 80. Acetato italiano grosso. Unisex.',
      ru: 'Смелая квадратная оправа в стиле 80-х. Толстый итальянский ацетат. Унисекс.',
    },
    description: {
      en: 'The 80s bold square is back — and it\'s no longer just a fashion statement. This chunky acetate frame makes a strong brand impression at retail, which translates to higher sell-through rates. The thick temples (6mm+) provide excellent surface area for deep engraving or metal inlay logos. Unisex sizing fits 95% of adult faces. Popular with streetwear brands, music festival merchandise, and fashion retailers.',
      zh: '80年代大胆方框回来了——它不仅是时尚声明。厚板材框在零售时给人强烈的品牌印象，带来更高的销售率。厚镜腿（6mm+）为深度雕刻或金属镶嵌logo提供了出色的表面面积。中性尺寸适合95%的成年人脸型。受潮牌、音乐节商品和时尚零售商欢迎。',
      es: 'El cuadrado boldly 80 ha regresado — y no es solo una declaración de moda.',
      fr: 'Le carré audacieux des années 80 est de retour — et ce n\'est pas qu\'une déclaration de mode.',
      pt: 'O quadrado ousado dos anos 80 está de volta — e não é apenas uma declaração de moda.',
      ru: 'Смелый квадрат 80-х вернулся — и это не просто модное заявление.',
    },
    price: '$3.20–7.50',
    priceRaw: { min: 3.2, max: 7.5, currency: 'USD' },
    moq: 3000,
    category: 'retro',
    tags: ['Unisex', 'Acetate', 'Vintage', 'Bold', 'Streetwear'],
    images: [
      'https://picsum.photos/seed/retro-square-main/800/600',
      'https://picsum.photos/seed/retro-square-side/800/600',
      'https://picsum.photos/seed/retro-square-detail/800/600',
      'https://picsum.photos/seed/retro-square-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Italian Acetate (6mm+ thick)',
      'Lens Material': 'CR39, 1.5mm',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Frame Width': '145mm',
      'Lens Height': '44mm',
      'Temple Thickness': '6mm',
      'Logo Area': 'Large — deep engraving / metal inlay',
      'Min Order': '3,000 pcs/model',
      'Production Time': '25–30 days',
      'Certifications': 'CE, FDA',
    },
    featured: false,
    badge: '',
    moqTiers: [
      { qty: '3,000–4,999', price: '$6.50–7.50' },
      { qty: '5,000–9,999', price: '$4.80–6.50' },
      { qty: '10,000+', price: '$3.20–4.80' },
    ],
  },
  {
    id: 'retro-round-lennon-001',
    name: {
      en: 'Retro Round — John Lennon Style',
      zh: '复古圆框 — 约翰列侬风格',
      es: 'Redondo Retro — Estilo John Lennon',
      fr: 'Rond Rétro — Style John Lennon',
      pt: 'Redondo Retrô — Estilo John Lennon',
      ru: 'Круглый Ретро — Стиль Джона Леннона',
    },
    shortDesc: {
      en: 'Iconic round frame in thin stainless steel. John Lennon-inspired vintage style.',
      zh: '标志性圆形镜框，薄不锈钢。约翰列侬风格复古款式。',
      es: 'Montura redonda icónica en acero inoxidable fino. Estilo vintage inspirado en John Lennon.',
      fr: 'Monture ronde emblématique en acier inoxydable fin. Style vintage inspiré de John Lennon.',
      pt: 'Armação redonda icônica em aço inoxidável fino. Estilo vintage inspirado em John Lennon.',
      ru: 'Культовая круглая оправа из тонкой нержавеющей стали. Винтажный стиль в духе Джона Леннона.',
    },
    description: {
      en: 'The round frame is the original icon — worn by John Lennon, Bob Dylan, and now every fashion-forward customer in your store. At just 26 grams, this is one of the lightest metal frames we produce. The thin wire temples give it an almost invisible profile from the front, while the slightly oversized round lenses (48mm) provide generous coverage. Sold consistently to European fashion boutiques and vintage-inspired retail concepts.',
      zh: '圆框是最初的标志——从约翰·列侬、鲍勃·迪伦，到如今您店里的每位时尚先锋顾客。仅重26克，是我们生产的最轻金属镜框之一。细线镜腿从正面看几乎隐形，而略大尺寸的圆形镜片（48mm）提供宽裕的覆盖范围。一直畅销欧洲时尚精品店和复古风格零售概念店。',
      es: 'La montura redonda es el icono original — desde John Lennon hasta hoy.',
      fr: 'La monture ronde est l\'icône originale — de John Lennon à aujourd\'hui.',
      pt: 'A armação redonda é o ícone original — de John Lennon até hoje.',
      ru: 'Круглая оправа — это оригинальная икона — от Джона Леннона до наших дней.',
    },
    price: '$3.00–6.50',
    priceRaw: { min: 3.0, max: 6.5, currency: 'USD' },
    moq: 3000,
    category: 'retro',
    tags: ['Unisex', 'Round', 'Metal', 'Vintage', 'Lightweight'],
    images: [
      'https://picsum.photos/seed/round-lennon-main/800/600',
      'https://picsum.photos/seed/round-lennon-side/800/600',
      'https://picsum.photos/seed/round-lennon-detail/800/600',
      'https://picsum.photos/seed/round-lennon-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Stainless Steel, 0.8mm wire',
      'Lens Material': 'CR39, 1.5mm',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Frame Width': '138mm',
      'Lens Diameter': '48mm',
      'Bridge': '20mm',
      'Weight': '26g',
      'Min Order': '3,000 pcs/model',
      'Production Time': '20–25 days',
      'Certifications': 'CE, FDA',
    },
    featured: false,
    badge: '',
    moqTiers: [
      { qty: '3,000–4,999', price: '$5.50–6.50' },
      { qty: '5,000–9,999', price: '$4.00–5.50' },
      { qty: '10,000+', price: '$3.00–4.00' },
    ],
  },
  {
    id: 'polarized-driving-001',
    name: {
      en: 'Driving Pro — Polarized Driving Rectangular',
      zh: '驾驶专业款 — 偏光驾驶矩形',
      es: 'Conducción Pro — Rectangular Polarizada',
      fr: 'Conduite Pro — Rectangulaire Polarisée',
      pt: 'Direção Pro — Retangular Polarizada',
      ru: 'Вождение Про — Поляризованный Прямоугольный',
    },
    shortDesc: {
      en: 'Eliminates 99% windshield glare. Classic rectangular shape. Polarized CR39.',
      zh: '消除99%挡风玻璃眩光。经典矩形款式。偏光CR39。',
      es: 'Elimina 99% del deslumbramiento del parabrisas. Forma rectangular clásica. CR39 polarizado.',
      fr: 'Élimine 99% des reflets du pare-brise. Forme rectangulaire classique.',
      pt: 'Elimina 99% do brilho do para-brisa. Formato retangular clássico.',
      ru: 'Устраняет 99% бликов лобового стекла. Классическая прямоугольная форма.',
    },
    description: {
      en: 'Every year, 3 million car accidents involve glare-related incidents. Professional drivers know that polarized driving lenses aren\'t just a comfort upgrade — they\'re a safety tool. Our driving-specific polarized lens uses a vertically oriented polarizer that blocks the horizontally reflected light from road surfaces and windshields. The rectangular metal frame is available in 3 finishes and fits medium-to-large faces well. The anti-reflective coating on the back of the lens eliminates the second-surface reflections that standard lenses suffer from.',
      zh: '每年有300万起事故涉及眩光相关事件。专业驾驶员知道偏光驾驶镜片不仅是舒适升级——更是安全工具。我们的驾驶专用偏光镜片使用垂直偏振器，阻挡来自路面和挡风玻璃的水平反射光。矩形金属框有3种饰面可选，适合中大脸型。镜片背面镀抗反射涂层，消除了标准镜片遭受的第二次表面反射。',
      es: '3 millones de accidentes al año involucran incidentes relacionados con el deslumbramiento.',
      fr: '3 millions d\'accidents par an impliquent des incidents liés aux reflets.',
      pt: '3 milhões de acidentes por ano envolvem incidentes relacionados ao brilho.',
      ru: 'Ежегодно 3 миллиона аварий связаны с инцидентами из-за бликов.',
    },
    price: '$4.50–10.00',
    priceRaw: { min: 4.5, max: 10.0, currency: 'USD' },
    moq: 3000,
    category: 'polarized',
    tags: ['Polarized', 'Driving', 'Safety', 'Metal', 'Unisex'],
    images: [
      'https://picsum.photos/seed/driving-main/800/600',
      'https://picsum.photos/seed/driving-car/800/600',
      'https://picsum.photos/seed/driving-lens/800/600',
      'https://picsum.photos/seed/driving-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Stainless Steel',
      'Lens Material': 'Polarized CR39 + AR coating (back)',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Glare Elimination': '99%',
      'Back AR Coating': 'Yes — eliminates secondary reflections',
      'Frame Width': '142mm',
      'Lens Height': '38mm',
      'Face Fit': 'Medium to Large',
      'Colors Available': '3 frame finishes',
      'Min Order': '3,000 pcs/model',
      'Production Time': '25–30 days',
      'Certifications': 'CE, FDA',
    },
    featured: false,
    badge: '',
    moqTiers: [
      { qty: '3,000–4,999', price: '$8.50–10.00' },
      { qty: '5,000–9,999', price: '$6.00–8.50' },
      { qty: '10,000+', price: '$4.50–6.00' },
    ],
  },
  {
    id: 'hiking-mountain-001',
    name: {
      en: 'Hiking & Mountaineering — Side Shields + Anti-fog',
      zh: '徒步登山款 — 侧挡板+防雾',
      es: 'Senderismo y Montañismo — Protectores + Anti-niebla',
      fr: 'Randonnée et Alpinisme — Protections Latérales + Anti-buée',
      pt: 'Caminhada e Montanhismo — Protetores + Anti-neblina',
      ru: 'Пеший Туризм и Альпинизм — Боковые Щитки + Антитуман',
    },
    shortDesc: {
      en: 'Side shields + anti-fog + anti-slip. Built for high altitude conditions.',
      zh: '侧挡板+防雾+防滑。为高海拔环境打造。',
      es: 'Protectores laterales + anti-niebla + antideslizante. Construido para condiciones de gran altitud.',
      fr: 'Protections latérales + anti-buée + antidérapant. Construit pour les conditions de haute altitude.',
      pt: 'Protetores laterais + anti-neblina + antiderrapante. Construído para condições de alta altitude.',
      ru: 'Боковые щитки + антитуман + антискольжение. Создан для высокогорных условий.',
    },
    description: {
      en: 'At altitude, UV radiation is 30-40% more intense than at sea level. This frame was designed specifically for mountaineering and high-altitude trekking. The polycarbonate lenses pass ANSI Z87.1 high-mass impact testing. Removable side shields attach in seconds for dusty trail conditions. The anti-fog coating maintains clear vision during steep climbs when温差大. Goggle-style strap compatibility for use over helmets.',
      zh: '在高海拔地区，紫外线辐射比海平面强30-40%。这款镜框专为登山和高海拔徒步设计。聚碳酸酯镜片通过ANSI Z87.1高重量冲击测试。可拆卸侧板几秒安装，用于多尘山路。防雾涂层在温差大时保持视野清晰。兼容护目镜式绑带，可戴在头盔外。',
      es: 'En altitud, la radiación UV es 30-40% más intensa. Esta montura fue diseñada específicamente para montañismo.',
      fr: 'En altitude, le rayonnement UV est 30-40% plus intense. Cette monture a été conçue pour l\'alpinisme.',
      pt: 'Em altitude, a radiação UV é 30-40% mais intensa. Esta armação foi projetada especificamente para montanhismo.',
      ru: 'На высоте УФ-излучение на 30-40% интенсивнее, чем на уровне моря. Эта оправа разработана специально для альпинизма.',
    },
    price: '$4.00–9.00',
    priceRaw: { min: 4.0, max: 9.0, currency: 'USD' },
    moq: 3000,
    category: 'sport',
    tags: ['Sports', 'Hiking', 'Mountaineering', 'Anti-fog', 'Side Shields', 'Impact Resistant'],
    images: [
      'https://picsum.photos/seed/hiking-main/800/600',
      'https://picsum.photos/seed/hiking-mountain/800/600',
      'https://picsum.photos/seed/hiking-lens/800/600',
      'https://picsum.photos/seed/hiking-pack/800/600',
    ],
    specs: {
      'Frame Material': 'TR90 + TPR Anti-slip',
      'Lens Material': 'Polycarbonate, 2mm (ANSI Z87.1)',
      'UV Protection': 'UV400 + Side Shields',
      'Impact Test': 'ANSI Z87.1 High Mass ✓',
      'Anti-fog': 'Yes — dual-ventilation system',
      'Side Shields': 'Removable — snaps on/off',
      'Strap Compatibility': 'Goggle strap fits over helmet',
      'Frame Width': '148mm',
      'Lens Height': '46mm',
      'Weight': '36g',
      'Min Order': '3,000 pcs/model',
      'Production Time': '25–30 days',
      'Certifications': 'CE, FDA, ANSI Z87.1',
    },
    featured: false,
    badge: '',
    moqTiers: [
      { qty: '3,000–4,999', price: '$7.50–9.00' },
      { qty: '5,000–9,999', price: '$5.50–7.50' },
      { qty: '10,000+', price: '$4.00–5.50' },
    ],
  },
  {
    id: 'kids-sport-active-001',
    name: {
      en: 'Kids Sport Active — Ages 8-16',
      zh: '儿童运动款 — 8-16岁',
      es: 'Infantil Deportivo Activo — 8-16A',
      fr: 'Enfant Sport Actif — 8-16 Ans',
      pt: 'Infantil Esportivo Ativo — 8-16A',
      ru: 'Детские Спортивные Активные — 8-16 Лет',
    },
    shortDesc: {
      en: 'Sport frame for older kids. Elastic strap + rubber temples. Shatterproof.',
      zh: '大童运动框。松紧带+橡胶镜腿。防碎。',
      es: 'Montura deportiva para niños mayores. Correa elástica + templos de goma. Irrompible.',
      fr: 'Monture sportive pour enfants plus âgés. Sangle élastique + branches en caoutchouc.',
      pt: 'Armação esportiva para crianças maiores. Alça elástica + hastes de borracha. Inquebrável.',
      ru: 'Спортивная оправа для детей старшего возраста. Эластичный ремешок + резиновые дужки.',
    },
    description: {
      en: 'Built for the 8-16 age group that destroys regular sunglasses. The TR90 frame is virtually unbreakable — it bends, snaps back, and keeps going. The wraparound design with elastic strap ensures a secure fit during soccer, cycling, skateboarding, and playground play. Rubber temple tips and nose pads prevent slipping during active use. Popular with sporting goods retailers and outdoor recreation brands.',
      zh: '为8-16岁群体打造，这个年龄段会毁掉普通太阳镜。TR90镜框几乎坚不可摧——弯曲后恢复原状，继续使用。环绕式设计和松紧带确保足球、骑行、滑板、操场玩耍时安全贴合。橡胶镜腿和鼻托防止运动时滑落。运动品零售商和户外休闲品牌欢迎。',
      es: 'Construido para el grupo de edad 8-16 que destruye las gafas de sol normales.',
      fr: 'Conçu pour le groupe d\'âge 8-16 qui détruit les lunettes de soleil ordinaires.',
      pt: 'Construído para o grupo etário 8-16 que destrói óculos de sol normais.',
      ru: 'Создан для возрастной группы 8-16, которая ломает обычные солнцезащитные очки.',
    },
    price: '$2.80–5.50',
    priceRaw: { min: 2.8, max: 5.5, currency: 'USD' },
    moq: 5000,
    category: 'kids',
    tags: ['Kids', 'Sport', 'Strap', 'Shatterproof', 'TR90', 'Ages 8-16'],
    images: [
      'https://picsum.photos/seed/kids-sport-main/800/600',
      'https://picsum.photos/seed/kids-sport-active/800/600',
      'https://picsum.photos/seed/kids-sport-colors/800/600',
      'https://picsum.photos/seed/kids-sport-pack/800/600',
    ],
    specs: {
      'Frame Material': 'TR90 + TPR Rubber',
      'Lens Material': 'Polycarbonate (Shatterproof)',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Strap': 'Elastic (38–52cm, adjustable)',
      'Age Range': '8–16 Years',
      'Anti-slip': 'TPR Rubber temples + nose pads',
      'Frame Width': '130mm',
      'Lens Height': '42mm',
      'Colors Available': '6 active colors',
      'Min Order': '5,000 pcs/model',
      'Production Time': '20–25 days',
      'Certifications': 'CE, FDA, CPSIA',
    },
    featured: false,
    badge: '',
    moqTiers: [
      { qty: '5,000–9,999', price: '$4.50–5.50' },
      { qty: '10,000–19,999', price: '$3.50–4.50' },
      { qty: '20,000+', price: '$2.80–3.50' },
    ],
  },
  {
    id: 'fashion-gradient-001',
    name: {
      en: 'Fashion Gradient — Beach-to-Street',
      zh: '时尚渐变款 — 海滩到街头',
      es: 'Moda Gradiente — De Playa a Calle',
      fr: 'Mode Dégradé — Plage à Rue',
      pt: 'Moda Gradiente — Praia para Rua',
      ru: 'Модные Градиентные — С Пляжа на Улицу',
    },
    shortDesc: {
      en: 'Light-to-dark gradient lenses. Fashionable enough for the city, functional for the beach.',
      zh: '浅至深渐变镜片。城市够时尚，海滩够实用。',
      es: 'Lentes degradadas claro a oscuro. Suficientemente fashionable para la ciudad, funcional para la playa.',
      fr: 'Verres dégradés clair à sombre. Suffisamment mode pour la ville, fonctionnel pour la plage.',
      pt: 'Lentes gradiente claro para escuro. Moderno o suficiente para a cidade, funcional para a praia.',
      ru: 'Линзы с градиентом от светлого к тёмному. Достаточно модные для города, функциональные для пляжа.',
    },
    description: {
      en: 'Gradient lenses were invented for driving — light at the top, dark at the bottom — and they\'ve been a fashion staple ever since. Our fashion gradient uses premium Italian acetate frames (because gradient lenses deserve better than injection-molded plastic) with scratch-resistant AR-coated CR39 gradient lenses. The fashion-forward cat-eye shape in 8 gradient colorways bridges beach and city seamlessly.',
      zh: '渐变镜片是为驾驶发明的——上浅下深——从此成为时尚标配。我们的时尚渐变款采用优质意大利板材框（因为渐变镜片值得更好的注塑塑料），配耐磨AR镀膜CR39渐变镜片。时尚猫眼形状8种渐变配色，无缝连接海滩和城市。',
      es: 'Los lentes degradados fueron inventados para conducir — claros arriba, oscuros abajo.',
      fr: 'Les verres dégradés ont été inventés pour la conduite — clairs en haut, sombres en bas.',
      pt: 'As lentes gradiente foram inventadas para direção — claras em cima, escuras embaixo.',
      ru: 'Градиентные линзы были изобретены для вождения — светлые сверху, тёмные снизу.',
    },
    price: '$3.50–7.80',
    priceRaw: { min: 3.5, max: 7.8, currency: 'USD' },
    moq: 3000,
    category: 'fashion',
    tags: ['Women', 'Gradient', 'Fashion', 'Acetate', 'Beach', 'AR Coated'],
    images: [
      'https://picsum.photos/seed/fashion-gradient-main/800/600',
      'https://picsum.photos/seed/fashion-gradient-beach/800/600',
      'https://picsum.photos/seed/fashion-gradient-lens/800/600',
      'https://picsum.photos/seed/fashion-gradient-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Italian Acetate',
      'Lens Material': 'CR39 Gradient + AR coating',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Gradient': 'Light top to dark bottom (fashion standard)',
      'Scratch Resistance': 'AR hard coat both sides',
      'Frame Width': '138mm',
      'Lens Height': '44mm',
      'Colors Available': '8 gradient colorways',
      'Min Order': '3,000 pcs/model',
      'Production Time': '25–30 days',
      'Certifications': 'CE, FDA',
    },
    featured: false,
    badge: '',
    moqTiers: [
      { qty: '3,000–4,999', price: '$6.50–7.80' },
      { qty: '5,000–9,999', price: '$5.00–6.50' },
      { qty: '10,000+', price: '$3.50–5.00' },
    ],
  },
  {
    id: 'luxury-gold-18k-001',
    name: {
      en: 'Luxury Signature — 18K Gold-Plated Diamond-Cut',
      zh: '奢华签名款 — 18K镀金钻石切割',
      es: 'Lujo Firma — Oro 18K Diamond-Cut',
      fr: 'Luxe Signature — Or 18K Découpe Diamant',
      pt: 'Luxo Assinatura — Ouro 18K Corte Diamante',
      ru: 'Люкс Сигнатура — 18K Позолота Алмазная Огранка',
    },
    shortDesc: {
      en: '18K gold-plated with diamond-cut temple pattern. Diamond-cut polarized mineral glass.',
      zh: '18K镀金，钻石切割镜腿图案。钻石切割偏光矿物玻璃。',
      es: 'Baño de oro 18K con patrón de templo de corte de diamante.',
      fr: 'Plaqué or 18K avec motif de branche découpé diamant.',
      pt: 'Banho de ouro 18K com padrão de haste cortado a diamante.',
      ru: 'Позолота 18K с узором дужек алмазной огранки.',
    },
    description: {
      en: 'This is the frame that builds luxury brands. The 18K gold plating process involves 7 steps: base polish, copper under-plate, nickel under-plate, 18K gold bath, protective lacquer, and hand inspection. The diamond-cut pattern on the temples catches light differently at every angle, creating a constantly shifting visual effect that customers notice and remember. Mineral glass lenses with full polarization provide the clearest vision of any lens material. This is the style that commands premium retail pricing.',
      zh: '这是打造奢华品牌的镜框。18K镀金工艺包括7个步骤：底漆抛光、铜底镀、镍底镀、18K金浴、保护面漆和手工检验。镜腿上钻石切割图案在不同角度捕捉光线不同，创造出不断变化的视觉效果，顾客会注意到并记住。矿物玻璃镜片配完整偏光，提供任何镜片材料中最清晰的视野。这是有底气做高端零售价的款式。',
      es: 'Este es el marco que construye marcas de lujo. El proceso de baño de oro 18K implica 7 pasos.',
      fr: 'C\'est la monture qui construit les marques de luxe. Le processus de placage or 18K implique 7 étapes.',
      pt: 'Esta é a armação que constrói marcas de luxo. O processo de banho de ouro 18K envolve 7 etapas.',
      ru: 'Это оправа, которая создаёт люксовые бренды. Процесс позолоты 18K включает 7 этапов.',
    },
    price: '$8.50–18.00',
    priceRaw: { min: 8.5, max: 18.0, currency: 'USD' },
    moq: 2000,
    category: 'luxury',
    tags: ['Luxury', 'Gold Plated', 'Diamond-Cut', 'Polarized', 'Mineral Glass', 'Premium'],
    images: [
      'https://picsum.photos/seed/luxury-gold-main/800/600',
      'https://picsum.photos/seed/luxury-gold-detail/800/600',
      'https://picsum.photos/seed/luxury-gold-lens/800/600',
      'https://picsum.photos/seed/luxury-gold-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Stainless Steel + 18K Gold (7-step plating)',
      'Lens Material': 'Polarized Mineral Glass, 1.8mm',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Plating Process': '7-step: polish → Cu → Ni → Au → lacquer',
      'Diamond-Cut Pattern': 'CNC-cut temple texture',
      'Frame Width': '142mm',
      'Lens Height': '44mm',
      'Weight': '32g',
      'Min Order': '2,000 pcs/model',
      'Production Time': '30–35 days',
      'Certifications': 'CE, FDA, ISO9001',
    },
    featured: false,
    badge: 'Luxury Best',
    moqTiers: [
      { qty: '2,000–4,999', price: '$14.00–18.00' },
      { qty: '5,000–9,999', price: '$11.00–14.00' },
      { qty: '10,000+', price: '$8.50–11.00' },
    ],
  },
  {
    id: 'aviator-oversized-001',
    name: {
      en: 'Oversized Aviator — Women\'s Bold Pilot',
      zh: '大框飞行员 — 女性大胆飞行员',
      es: 'Aviador Oversize — Piloto Audo Mujer',
      fr: 'Aviateur Oversize — Pilote Audacieux Femme',
      pt: 'Aviador Tamanho Grande — Piloto Ousado Mulher',
      ru: 'Большой Авиатор — Смелый Женский Пилот',
    },
    shortDesc: {
      en: 'Oversized pilot frame with pearl temple detail. Bold, unapologetic femininity.',
      zh: '大框飞行员款，珍珠镜腿细节。大胆、无畏的女性气质。',
      es: 'Montura piloto oversize con detalle de templo de perla. Feminidad audaz e impecable.',
      fr: 'Monture pilote surdimensionnée avec détail de branche en perle. Féminité audacieuse.',
      pt: 'Armação piloto grande com detalhe de haste de pérola. Feminilidade ousada e inequívoca.',
      ru: 'Большая пилотская оправа с деталью жемчужной дужки. Смелая, бескомпромиссная женственность.',
    },
    description: {
      en: 'The oversized aviator is the frame that says \'I know what I want.\' The larger proportions (lens height 52mm vs standard 48mm) create a bold statement that photographs well — critical for Instagram-era fashion brands. Pearl temple tips are hand-set by our craftspeople, adding a distinctive detail that justifies premium positioning. The gold metal frame with warm-toned polarized lenses creates a cohesive luxury look.',
      zh: '大框飞行员是说"我知道我要什么"的款式。更大的比例（镜片高度52mm vs 标准48mm）创造出大胆宣言，拍照效果好——这对Instagram时代的时尚品牌至关重要。珍珠镜腿尖端由工匠手工镶嵌，添加了独特细节，支撑高端定位。金色金属框配暖色调偏光镜片打造统一奢华外观。',
      es: 'El aviador oversize es la montura que dice "sé lo que quiero." Proporciones más grandes, fotografía mejor.',
      fr: 'L\'aviateur oversize est la monture qui dit "je sais ce que je veux." Plus grandes proportions, meilleure photo.',
      pt: 'O aviador grande é a armação que diz "eu sei o que quero." Proporções maiores, fotografa melhor.',
      ru: 'Большой авиатор — это оправа, которая говорит "я знаю, чего хочу." Увеличенные пропорции лучше смотрятся на фото.',
    },
    price: '$4.00–9.00',
    priceRaw: { min: 4.0, max: 9.0, currency: 'USD' },
    moq: 3000,
    category: 'classic-aviator',
    tags: ['Women', 'Oversized', 'Metal', 'Pearl Detail', 'Polarized', 'UV400'],
    images: [
      'https://picsum.photos/seed/aviator-ovs-main/800/600',
      'https://picsum.photos/seed/aviator-ovs-side/800/600',
      'https://picsum.photos/seed/aviator-ovs-pearl/800/600',
      'https://picsum.photos/seed/aviator-ovs-pack/800/600',
    ],
    specs: {
      'Frame Material': 'Metal Alloy + 18K Gold + Pearl (hand-set)',
      'Lens Material': 'Polarized CR39, 1.5mm',
      'UV Protection': 'UV400 (UVA + UVB)',
      'Lens Height': '52mm (oversized)',
      'Frame Width': '145mm',
      'Bridge': '16mm',
      'Pearl Detail': 'Hand-set on both temples',
      'Colors Available': 'Gold/Pearl + Gunmetal/Pearl',
      'Min Order': '3,000 pcs/model',
      'Production Time': '25–30 days',
      'Certifications': 'CE, FDA, ISO9001',
    },
    featured: false,
    badge: 'Women\'s Pick',
    moqTiers: [
      { qty: '3,000–4,999', price: '$7.50–9.00' },
      { qty: '5,000–9,999', price: '$5.50–7.50' },
      { qty: '10,000+', price: '$4.00–5.50' },
    ],
  },
];

export function getProductsByCategory(category: string): Product[] {
  if (category === 'all') return products;
  return products.filter(p => p.category === category);
}

export function getProductById(id: string): Product | undefined {
  return products.find(p => p.id === id);
}

export function getFeaturedProducts(): Product[] {
  return products.filter(p => p.featured);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return products
    .filter(p => p.id !== product.id && (p.category === product.category || p.tags.some(t => product.tags.includes(t))))
    .slice(0, limit);
}

export function searchProducts(query: string, lang: Language): Product[] {
  const q = query.toLowerCase();
  return products.filter(p =>
    p.name[lang].toLowerCase().includes(q) ||
    p.shortDesc[lang].toLowerCase().includes(q) ||
    p.tags.some(t => t.toLowerCase().includes(q))
  );
}

export const categories = [
  { key: 'all', label: { en: 'All Products', zh: '全部产品', es: 'Todos', fr: 'Tous', pt: 'Todos', ru: 'Все' } },
  { key: 'classic-aviator', label: { en: 'Classic Aviator', zh: '经典飞行员', es: 'Aviador Clásico', fr: 'Aviateur', pt: 'Aviador', ru: 'Авиатор' } },
  { key: 'sport', label: { en: 'Sport', zh: '运动款', es: 'Deportivo', fr: 'Sport', pt: 'Esportivo', ru: 'Спорт' } },
  { key: 'cat-eye', label: { en: 'Cat Eye', zh: '猫眼', es: 'Ojo de Gato', fr: 'Chat', pt: 'Olho de Gato', ru: 'Кошачий' } },
  { key: 'kids', label: { en: 'Kids', zh: '儿童', es: 'Infantil', fr: 'Enfants', pt: 'Infantil', ru: 'Детские' } },
  { key: 'luxury', label: { en: 'Luxury', zh: '奢华款', es: 'Lujo', fr: 'Luxe', pt: 'Luxo', ru: 'Люкс' } },
  { key: 'retro', label: { en: 'Retro', zh: '复古', es: 'Retro', fr: 'Rétro', pt: 'Retrô', ru: 'Ретро' } },
  { key: 'polarized', label: { en: 'Polarized', zh: '偏光', es: 'Polarizada', fr: 'Polarisé', pt: 'Polarizado', ru: 'Поляризованные' } },
  { key: 'fashion', label: { en: 'Fashion', zh: '时尚', es: 'Moda', fr: 'Mode', pt: 'Moda', ru: 'Модные' } },
] as const;

export const clientLogos = [
  { name: 'OptiWorld', country: 'Germany' },
  { name: 'SunStyle Co.', country: 'USA' },
  { name: 'Vision Plus', country: 'UK' },
  { name: 'Optical Express', country: 'Canada' },
  { name: 'ClearView', country: 'Australia' },
  { name: 'Eyewear Depot', country: 'USA' },
  { name: 'Solar Glasses GmbH', country: 'Germany' },
  { name: 'Vista Mar', country: 'Brazil' },
  { name: 'Opticalia', country: 'Spain' },
  { name: 'SunGuard ME', country: 'UAE' },
  { name: 'Eyezone', country: 'South Africa' },
  { name: 'Optic Style', country: 'France' },
];

export const testimonials = [
  {
    id: '1',
    author: { name: 'Michael Torres', company: 'OptiWorld GmbH', country: 'Germany' },
    text: {
      en: 'Guangwei has been our primary sunglasses supplier for 6 years. The quality consistency across 200,000+ pairs has been exceptional — less than 0.1% defect rate. Their team handles everything professionally.',
      zh: '光威是我们主要的太阳镜供应商，已经合作6年。20万+副的品质一致性非常出色——缺陷率低于0.1%。他们的团队专业处理一切。',
    },
    rating: 5,
    product: 'Classic Aviator Gold Metal',
    year: '2024',
  },
  {
    id: '2',
    author: { name: 'Sarah Chen', company: 'SunStyle Co.', country: 'USA' },
    text: {
      en: 'We switched from our previous supplier to Guangwei and immediately noticed the quality improvement. The sample development was fast and their MOQ flexibility made it easy to test new styles before committing to full production runs.',
      zh: '从之前的供应商切换到光威后，我们立即注意到品质改善。样品开发很快，他们的起订量灵活性让我们在全量生产前轻松测试新款式。',
    },
    rating: 5,
    product: 'Cat Eye Italian Acetate',
    year: '2024',
  },
  {
    id: '3',
    author: { name: 'James Wright', company: 'ClearView Australia', country: 'Australia' },
    text: {
      en: 'The kids\' sunglasses from Guangwei are our best-selling children\'s eyewear line. Parents love the shatterproof lenses and adjustable strap. The CE and FDA certifications give us complete confidence in safety compliance.',
      zh: '光威的儿童太阳镜是我们最畅销的儿童眼镜系列。家长喜欢防碎镜片和可调节绑带。CE和FDA认证让我们对安全合规完全放心。',
    },
    rating: 5,
    product: 'Kids Safe Shatterproof',
    year: '2023',
  },
];
